### ISSUE TITLE
¿Cómo agregar las imágenes al layout? 

### ISSUE THREAD

**Issue by aton1698** [LabExperimental-SIUA/osmtracker-android#14]

**Comment by EmmanuelAB** [comment]
yo pude ponerle iconos al layout de ejemplo que sale en el wiki https://github.com/nguillaumin/osmtracker-android/wiki. Lo que hice fue conseguir el icono deseado en png y ponerlo dentro de la carpeta "layouts" luego como atributo del boton en el xml se pone <code>"icon=img.png"</code> luego se selecciona el layout desde la app y listo. Hay que tener en cuenta el tamaño del icono porque si es muy grande queda muy desproporcionado con respecto a los demás botones. Ví como hacer esto en el wiki que mencioné arriba puede que ahí esté mejor explicado lo que esto diciendo aquí.

**Comment by jamescr** [comment]
¿Esas imágenes son las "oficiales" de la aplicación, o las que puso fueron las que había hecho Esteban?

**Comment by jamescr** [comment]
On Thu, Aug 31, 2017 at 4:45 PM, EmmanuelAB <notifications@github.com>
wrote:

> En realidad puse iconos ahí random. Puedo intentar con los que hicieron
> para ver que tal quedan si le parece
>

Si, inténtelo.

**Comment by EmmanuelAB** [comment]
donde puedo bajarlos?

**Comment by jamescr** [comment]
On Thu, Aug 31, 2017 at 4:58 PM, EmmanuelAB <notifications@github.com>
wrote:

> donde puedo bajarlos?
>

Se las pasé por Telegram.

**Comment by jamescr** [comment]
Por acá documenté las decisiones que hemos tomado: https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Gu%C3%ADa-para-crear-Layout

**Comment by jamescr** [comment]
Si alguno tiene alguna cosa más para compartir sobre este tema, agréguelo en el [wiki](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Gu%C3%ADa-para-crear-Layout).
