### ISSUE TITLE
Documentar generación de apk

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#15]
La semana pasada estuvieron generando un APK a partir del código fuente del LabExp/master. Cada uno de los tres tenía que hacerlo por su cuenta y al finalizar cerraron su issue. 

Para que ese conocimiento perdure, documenten el proceso en la wiki de este repositorio. En este issue pueden coordinar el desarrollo de esta tarea.

**Comment by altaros97** [comment]
Una vez que se crea la wiki se puede editar, ¿verdad?, si ese es el caso entonces yo ahorita la creo, coloco que problemas tuve y lo demás del proceso de creación e instalación. Luego cada uno pone sus procesos, ¿les parece?

**Comment by jamescr** [comment]
Si la wiki la podemos editar todos. Creo que para resolver este issue deben coordinar y repartirse roles. Uno debe crearla y hacer una estructura inicial, cada uno debe incluir ahí los aspectos más relevantes y alguien debe darle una revisada final para estar seguro que todo tiene sentido como una unidad.

**Comment by EmmanuelAB** [comment]
Me parece bien la idea del wiki

**Comment by altaros97** [comment]
> Deberíamos poner una fecha para que todos hayan agregado sus procesos.

Yo diría que este miércoles 30 de agosto a más tardar a las 8:00 p.m

**Comment by EmmanuelAB** [comment]
Esta bien

**Comment by altaros97** [comment]
Listo!! Ya creé el wiki, @jamescr no sé si de esta manera está bien.

**Comment by altaros97** [comment]
Tarea completada

**Comment by jamescr** [comment]
Está buenísimo. Le veo pinta de post de blog, Lo cual deberíamos aprovechar y publicarlo en el blog del laboratorio. 

Voy a volver a abrir el issue para que le corrijan un detalle. En esta tarea deben de colabora entre ustedes para que se lea como una unidad de cómo completar la tarea y no la versión de cada uno. 

El viernes en la reunión podemos hablar de estas dos cosas.

**Comment by altaros97** [comment]
Wiki corregido.

**Comment by jamescr** [comment]
👌
