### ISSUE TITLE
Documentar cómo agregar layout de Alajuela

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#16]
En la [página](https://wiki.openstreetmap.org/wiki/ES:Alajuela) sobre Alajuela  del wiki de Open StreetMap hemos puesto alguna documentación para usuarios que quieran colaborar con varios proyectos que tenemos en curso. Por ahí se sugiere instalar el layout de Alajuela en la herramienta, pero no es muy claro (también se explica [cómo mapear con OSMTracker](https://wiki.openstreetmap.org/wiki/ES:Alajuela_OSMTracker)).

¿Qué tal si la mejoran un poco esa wiki?

**Comment by altaros97** [comment]
Me parece!

**Comment by EmmanuelAB** [comment]
ya terminé la pagina correspondiente a este issue en el wiki. Si pueden revísenlo y si tienen cualquier sugerencia o cambio a favor les agradezco

**Comment by jamescr** [comment]
>ya terminé la pagina correspondiente a este issue en el wiki del lab. Si pueden revísenlo y si tienen cualquier sugerencia o cambio a favor les agradezco. 

Me parece que el wiki está bien. Solamente hay un detalle, al dar clic en el enlace al xml no me inicia la descarga de forma automática. 

>También ¿Que les parece si ponemos un link a esta pagina del wiki del lab, en el wiki de Alajuela en OSM? Porque ahí mencionan que se usa osm-tracker y el layout de Alajuela pero no explica cómo unir las dos cosas

Me parece excelente.

**Comment by EmmanuelAB** [comment]
y si mantiene presionado el enlace y luego le da "descargar enlace"?

**Comment by jamescr** [comment]
El 02/09/2017 10:59, "EmmanuelAB" <notifications@github.com> escribió:

y si mantiene presionado el enlace y luego le da "descargar enlace"?


En mi teléfono no me da la opción de "descargar enlace"...


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LabExperimental-SIUA/osmtracker-android/issues/16#issuecomment-326756506>,
or mute the thread

**Comment by altaros97** [comment]
Igualmente, deberia de cambiar donde dice

> Mantenga pulsado el siguiente link al archivo

Ya que no todos lo van a descargar desde un móvil, por el momento no sería más conveniente subirlo a una nube como DropBox, Drive o Mega para así poner un link de descarga exacto para todos los dispositivos?

**Comment by EmmanuelAB** [comment]
ya agregué el enlace al tutorial para agregar el layout de alajuela, en el wiki Alajuela en OSM. Ya se ve en la sección de herramientas ->  https://wiki.openstreetmap.org/wiki/ES:Alajuela

**Comment by jamescr** [comment]
Buenísimo.
