### ISSUE TITLE
Grabar traza y subir a OSM

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#17]
Para probar la funcionalidad del OSMTracker que permite subir trazas (gpx) al servidor de Open Street Map van a hacer lo siguiente:

-  Mapeo: grabar una traza (gpx) utilizando OSMTracker y agreguen varios elementos en la traza (por ejemplo: notas que digan dónde están las aulas de las sede, parqueos para personas con discapacidad, hidrantes, etc).

- Van a subir la traza a OSM utilizando las opciones que brinda el OSM Tracker. Para esto deben tener un usuario de Open Street Map. 

(opcional: siéntanse libres de modificar cualquier wiki dónde se explique cómo llevar a cabo esas tareas).

**Comment by EmmanuelAB** [comment]
Listo, traza subida sin problemas

**Comment by aton1698** [comment]
Listo también

**Comment by altaros97** [comment]
LIsto

**Comment by jamescr** [comment]
¿Pueden poner por acá el URL de OSM que me lleva a la traza que subieron?

**Comment by aton1698** [comment]
https://www.openstreetmap.org/user/Brandon%20Oviedo/traces/2496557
[https://www.openstreetmap.org/assets/osm_logo_256-835a859acf0d378e1d14e88b15e7b4b95211ccd41a2c061b1629cfbbb8deb697.png]<https://www.openstreetmap.org/user/Brandon%20Oviedo/traces/2496557>

OpenStreetMap | Viewing trace Sep_7__2017_2_47_55_PM_2017_09_07_14_47_55.gpx<https://www.openstreetmap.org/user/Brandon%20Oviedo/traces/2496557>
OpenStreetMap is a map of the world, created by people like you and free to use under an open license.
www.openstreetmap.org



________________________________
De: Jaime Gutiérrez Alfaro <notifications@github.com>
Enviado: jueves 14 de septiembre de 2017 06:36 p.m.
Para: LabExperimental-SIUA/osmtracker-android
Cc: aton1698; Assign
Asunto: Re: [LabExperimental-SIUA/osmtracker-android] Grabar traza y subir a OSM (#17)


¿Pueden poner por acá el URL de OSM que me lleva a la traza que subieron?

**Comment by EmmanuelAB** [comment]
https://www.openstreetmap.org/user/Emmanuelab/traces/2497143

**Comment by jamescr** [comment]
@altaros97 cuando tenga chance sube la traza.

**Comment by altaros97** [comment]
Lo siento Profe, la iba a subir pero se me había olvidado hacerlo. https://www.openstreetmap.org/user/altaros97/traces/2497294
