### ISSUE TITLE
Aprender Android

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#18]
Ver los primeros12 videos del enlace https://www.youtube.com/watch?v=pdYkmCcQFd8&list=PLU8oAlHdN5Bkn-KS1sRFlSEnXXcAtAJ9P

- Revisar la documentación de desarrolladores de android.

**Comment by EmmanuelAB** [comment]
https://developer.android.com/guide/components/fundamentals.html

**Comment by aton1698** [comment]
Listo

**Comment by altaros97** [comment]
Listo

**Comment by EmmanuelAB** [comment]
Listo

**Comment by jamescr** [comment]
A mi aún me faltan 3.  😞

**Comment by altaros97** [comment]
Y eso era para la semana pasada!! jaja

**Comment by jamescr** [comment]
Si... voy mal. 😭

**Comment by EmmanuelAB** [comment]
Perdón lo cerré por un dedaso.
