### ISSUE TITLE
Crear layout de hidrantes

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#19]
Crear un layout en su repositorio. Cuando esté listo hacer un PR al branch `layouts` del repositorio `LabExperimental-SIUA/osmtracker-android`.

**Comment by aton1698** [comment]
Listo

**Comment by jamescr** [comment]
Le dejé un comentario en el [PR](https://github.com/LabExperimental-SIUA/osmtracker-android/pull/29) para que lo arregle y así hacer el merge.

**Comment by aton1698** [comment]
Ya realicé el cambio de nombre en la carpeta
