### ISSUE TITLE
Crear layout transporte público

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#20]
Crear un layout en su repositorio. Cuando esté listo hacer un PR al branch `layouts` del repositorio `LabExperimental-SIUA/osmtracker-android`.

**Comment by altaros97** [comment]
@jamescr ¿No me prodría volver a indicar los pasos para realizar el pull request?, según yo tenía que crear una rama nueva dentro de mi repositorio local y ahí agregar el layout junto con los iconos, luego realizar un push de eso en la rama que cree y por último realizar el pull request hacia el repo del Lab Experimental en la rama layouts pero no estoy seguro de que sea de esa forma.

**Comment by jamescr** [comment]
Si. esa es la forma que acordamos.  El paso de hacer el PR (pull request) se hace en el sitio web. El cuidado que hay que tener es hacer el PR al repo del laboratorio y no al repo de nguillaumin.

**Comment by altaros97** [comment]
Ok, gracias.

**Comment by altaros97** [comment]
Listo!! Se lo asigné a usted para que revise que no haya ningún error.

**Comment by jamescr** [comment]
No me había dado cuenta que me lo asignó, he estado un poco tallado de tiempo.  
En todo caso ya vi que le hizo _merge_. A futuro, le puede asignar el PR a más de uno, pues lo ideal es que no sea la misma persona la que crea y acepta el PR.
