### ISSUE TITLE
Crear layout de accesibilidad

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#21]
Crear un layout en su repositorio. Cuando esté listo hacer un PR al branch `layouts` del repositorio `LabExperimental-SIUA/osmtracker-android`.

**Comment by jamescr** [comment]
Por error aceptamos el [PR](https://github.com/LabExperimental-SIUA/osmtracker-android/pull/32) que había merge al `master`. Ya restablecimos el código del repo, pero necesitamos que vuelta a hacer el Pull Request (al branch `layouts`)

**Comment by EmmanuelAB** [comment]
listo

**Comment by jamescr** [comment]
Interesante artículo: https://blog.ldodds.com/2017/09/19/mapping-wheelchair-accessibility-how-google-could-help/
