### ISSUE TITLE
Wiki - layout hidrantes

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#22]
Explicar el significado e los botones del layout en el [wiki de Alajuela en OSM](http://wiki.openstreetmap.org/wiki/ES:Alajuela).

**Comment by aton1698** [comment]
Listo

**Comment by jamescr** [comment]
Dejo por acá el [URL del wiki](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Disposici%C3%B3n-de-botones-en-Layout-para-el-mapeo-de-hidrantes.) para dejar el issue auto documentado.
