### ISSUE TITLE
Wiki - layout transporte público

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#23]
Explicar el significado de los botones del layout en el [wiki de Alajuela en OSM](http://wiki.openstreetmap.org/wiki/ES:Alajuela).

**Comment by altaros97** [comment]
Aquí se encuentra el wiki de transporte público https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Disposici%C3%B3n-de-botones-en-Layout-para-el-mapeo-de-Transporte-P%C3%BAblico 

Solo me falta agregar dos imagenes (ciclovia inicio y ciclovia fin), además, de la pantalla principal cuando se comienza a mapear

**Comment by altaros97** [comment]
Listo, ye el wiki de Transporte Público está completo
