### ISSUE TITLE
Wiki - accesibilidad

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#24]
Explicar el significado de los botones del layout en el [wiki de Alajuela en OSM](http://wiki.openstreetmap.org/wiki/ES:Alajuela).

**Comment by jamescr** [comment]
PSI. Video sobre accesibilidad: https://archive.org/details/jaquerespeis-mapas

**Comment by EmmanuelAB** [comment]
listo

**Comment by jamescr** [comment]
Solo para que este issue quede autodocumentado dejo por acá el link al [wiki](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Disposici%C3%B3n-de-botones-en-Layout-para-mapeo-de-Accesibilidad)
