### ISSUE TITLE
Aprender Android II

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#25]
Ver los videos 13 al 24 del enlace https://www.youtube.com/watch?v=pdYkmCcQFd8&list=PLU8oAlHdN5Bkn-KS1sRFlSEnXXcAtAJ9P

- Revisar la documentación de desarrolladores de Android.

**Comment by altaros97** [comment]
Listo!!

**Comment by EmmanuelAB** [comment]
Listo

**Comment by aton1698** [comment]
Listo
