### ISSUE TITLE
Aprender Android III

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#30]
Ver los videos 25 al 36 del enlace https://www.youtube.com/watch?v=pdYkmCcQFd8&list=PLU8oAlHdN5Bkn-KS1sRFlSEnXXcAtAJ9P

**Comment by altaros97** [comment]
Listo!!

**Comment by EmmanuelAB** [comment]
listo

**Comment by aton1698** [comment]
Listo
