### ISSUE TITLE
Propuesta de abordaje instalación automática de layouts

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#31]
Comentario/Anuncio: En el [wiki](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki) documente las tareas que estamos llevando a cabo. Como verán ya tenemos la tarea1 prácticamente lista y la 4 está caminando.

La idea de este issue es que, tomando en cuenta los conocimientos adquiridos de Android, el conocimiento práctico de OSMTracker y alguna otra investigación que puedan llevar a cabo, preparen una propuesta de abordaje y solución a la tarea 2 (documentada en el [wiki](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki)). Esta propuesta la comentaremos el viernes durante la reunión, la pueden trabajar de manera individual o en grupo.

**Comment by jamescr** [comment]
Propuesta de archivo XML de metadatos:

~~~
<lang>
    <es>
        <name>Español</name>
        <desc>Descripción en menos de 200 palabras</desc>
    </es>
    <en>
        <name>English</name>
        <desc>Description in less than 200 words</desc>
    </en>
</lang>
~~~

**Notas:**

* Las etiquetas bajo `lang` deben seguir el código ISO para lenguajes. 
* El archivo del `layout` correspondiente al idioma tendrá el mismo nombre que el archivo de metadatos, pero se le agregará el postfijo guión bajo + el código idioma.  Por ejemplo para un archivo de metadatos `hidrantes.xml` el archivo con el layout en idioma español se llamará `hidrantes_es.xml`.  

**Pendientes:**

* Queda pendiente documentar esto en el [wiki] (https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Gu%C3%ADa-para-crear-Layout)
* Mejorar la documentación de la estructura de carpetas. 

**Acuerdos**
* Por decisión unánime hemos decido que @altaros97 se encargará de los issues de la semana6 y nos hará un resumen de los videos de pildoras informáticas ;-)

**Comment by altaros97** [comment]
No me parece el último acuerdo, ni si quiera me he visto un solo video! jaja
