### ISSUE TITLE
Aprender Android IV

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#35]
Ver los videos 26 al 48 del enlace https://www.youtube.com/watch?v=pdYkmCcQFd8&list=PLU8oAlHdN5Bkn-KS1sRFlSEnXXcAtAJ9P

**Comment by EmmanuelAB** [comment]
Listo

**Comment by altaros97** [comment]
Listo!!

**Comment by aton1698** [comment]
Listo
