### ISSUE TITLE
Actualizar wiki "Guía para crear Layout"

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#39]
Tomando en cuenta las decisiones de diseño de las últimas dos semanas actualizar el [wiki "Guía para crear Layout"](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Gu%C3%ADa-para-crear-Layout), específicamente ser claro en la estructura de carpetas y archivos. 

Reviser el issue #31.

**Comment by aton1698** [comment]
Ya actualicé el wiki, revisar si cumple con lo que habíamos hablado

**Comment by altaros97** [comment]
@aton1698 Tiene un error en la explicación de carpetas, lo de la carpeta metadatos no va a estar dentro del teléfono sino dentro del servidor (GitHub) en una carpeta llamada layouts. Lo que va a tener el teléfono es lo mismo de siempre, solo el -xml y la carpeta con iconos.

**Comment by aton1698** [comment]
Cierto, pero entonces creo que sería mejor cambiar el título del wiki, ya que el proceso que estaba era para usar un layout y no para crearlo. O bien, se podría crear dentro del mismo wiki (u otro especifico para el uso por ahora de un layout) la explicación para el uso de un layout y otro para los estándares a seguir a la hora de hacer un propio layout

**Comment by aton1698** [comment]
Ya realicé los cambios e hice la separación de los wiki, si consideran que no es lo ideal, o pondríamos cambiar de nuevo

**Comment by jamescr** [comment]
Creo que ambas cosas, (1) estructura de archivos del layout en el celular y (2) estructura de archivos del repo, deberían estar en el mismo wiki.  Y ambas cosas deberían ser bastante claras. 

(Por otra parte voy a abrir un issue nuevo para unificar en una sola página los wikis de "disposiciones de botones en layout ...")

**Comment by jamescr** [comment]
hice algunos cambios de estilo acá: "Guía para crear Layout"

**Comment by aton1698** [comment]
Ya realicé los cambios en el wiki, espero a que lo revisen para ver si se le hacen más cambios

**Comment by altaros97** [comment]
Siento que el concepto de la estructura está bien explicado, solo que me parece que sería mejor si explica primero el propósito de cada archivo y carpeta y luego específica cuál es el formato que debe de seguir cada uno.

**Comment by jamescr** [comment]
> Siento que el concepto de la estructura está bien explicado, solo que me parece que sería mejor si explica primero el propósito de cada archivo y carpeta y luego específica cuál es el formato que debe de seguir cada uno.

no entendí.

**Comment by altaros97** [comment]
A lo que me refería era que sería más conveniente separar la explicación de qué es cada archivo del formato que este tiene que llevar.

**Comment by jamescr** [comment]
¿Un ejemplo?

**Comment by altaros97** [comment]
**Explicación de carpetas y archivos**  
- **carpeta layouts**: Esta carpeta contendrá todos los archivos layout en formato xml (la disposición de botones), carpeta con iconos para cada layout (si es que se agrega) y una carpeta de metadatos.
- **archivo layout**: este archivo contendrá la disposición de botones para cada layout que se quiera realizar.... etc.  
- **carpeta con iconos**: dentro de esta carpeta se almacenarán los iconos pertenecientes a un layout en especifico, es decir, una carpeta por cada layout que exista (en caso de que el layout incluya iconos).  
- **carpeta metadatos**: dentro de esta carpeta se almacenarán archivos con información de cada layout (recordemos que un mismo layout va a estar en diferentes idiomas, no obstante, solo se necesitará un archivo para representar a todos).  
- **archivo metadatos**: este archivo contendrá una descripción del layout (una descripción en cada idioma por cada idioma en que esté el layout).
  
**Formatos a seguir**  
- **archivo layout**: este archivo se debe de escribir en formato xml como se especifica en el upstream de OSMTracker (ver repositorio), además, debe contar con un nombre significativo (ej: hidrantes.xml), en caso de tener espacios colocar un "_" en lugar de los espacios (ej: transporte_publico.xml) y si el layout está en diferentes idiomas se debe de colocar el ISO del idioma luego del nombre (ej: hidrantes_es.xml, hidrantes_en.xml, etc.).  
- **carpeta iconos**: el nombre de esta carpeta debe ser igual al nombre del layout (nombre significativo), por ejemplo, si el layout se llama <code>hidrantes_es.xml, hidrantes_en.xml</code> la carpeta se llamará <code>hidrantes</code>  
  
  
Y así con los demás archivos y carpetas.
