### ISSUE TITLE
Modificar layouts personalizados

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#40]
Una vez que se haya actualizado el [wiki "Guía para crear Layout"](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Gu%C3%ADa-para-crear-Layout) (ver issue #39), actualizar los layouts:

- Hidrantes ( @aton1698 )

- Transporte público ( @altaros97 )

- Accesibiliad ( @EmmanuelAB )

nota: recuerden subirlo al branch `layouts`

**Comment by altaros97** [comment]
¡LIsto! solo falta que revisen el pull request.

**Comment by jamescr** [comment]
ver PR #52
