### ISSUE TITLE
Traducir documentación y generar pantallazos

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#42]
Traducir a inglés los textos del archivo de pencil (branch  `docu`).  Guardar el archivo con el prefijo "<nombre>_en<extensión>"

Hacer una carpeta "screenshots" y guardar un par de pantallazos traducidos a inglés.

**Comment by EmmanuelAB** [comment]
Creo que esto ya está listo :+1:

**Comment by jamescr** [comment]
[listo](https://github.com/LabExperimental-SIUA/osmtracker-android/pull/45).
