### ISSUE TITLE
páginas del wiki "disposiciones de botónes en layout..."

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#46]
Actualmente hay 3 páginas donde se explican las disposiciones de botones, para cada uno de los layouts que tenemos. Este issue es para valorar si unimos esas tres páginas en una sola.

**Comment by altaros97** [comment]
No estaría mal unirlos, quizás así se pueda hacer referencia a las 3 disposiciones más fácilmente

**Comment by jamescr** [comment]
(nota: el issue no tiene nadie asignado ;-) )

**Comment by EmmanuelAB** [comment]
Me parece que los 3 hablan de algo similiar, aunque mapean cosas diferentes al fin los 3 articulos explican un layout, me parece buena idea unirlos en uno sólo

**Comment by altaros97** [comment]
Si todos estamos de acuerdo en unir los wiki entonces yo voy a crear la página y voy a color mi parte y que @aton1698 y @EmmanuelAB coloquen lo suyo después.

**Comment by EmmanuelAB** [comment]
el mío ya está fusionado

**Comment by aton1698** [comment]
Ya también agregué el mio
