### ISSUE TITLE
Wiki duplicada y posible contenido inconsistente

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#53]
Las wikis "[Guía para crear Layout](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Gu%C3%ADa-para-crear-Layout)" y "[Guide to create Layouts](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Guide-to-create-Layouts)"  son un potencial problema. Pues fácilmente una quedará desactualizada con respecto a la otra y además existe la posibilidad de que se generen inconsistencia como [ya](https://github.com/LabExperimental-SIUA/osmtracker-android/pull/52) lo reportó acá Adrián. 

Dado que es de esperar una mayor interacción con otros colaboradores de osmtracker-android, sugiero que eliminemos la página en españo.

**Comment by EmmanuelAB** [comment]
Sí... Además en estas comunidades es bastante más común el inglés que es español

**Comment by altaros97** [comment]
Estoy de acuerdo.

**Comment by jamescr** [comment]
Si @aton1698 también está de acuerdo entonces borramos la página en español. (le podemos asignar eso a brandon por responder de último).

**Comment by aton1698** [comment]
Está bien, ya lo borro
