### ISSUE TITLE
Descargar archivo desde URL.

### ISSUE THREAD

**Issue by aton1698** [LabExperimental-SIUA/osmtracker-android#59]
Creación de un código para descargar archivos desde un URL, útil para las actualizaciones de layouts, descargar los metadatos y el archivo xml en si.

**Comment by aton1698** [comment]
Lo pueden ver [aquí]("https://github.com/aton1698/osmtracker-android/tree/descarga")

**Comment by aton1698** [comment]
Los parámetros para la descarga serán el `url` de descarga del archivo, una bandera para saber si se desea descargar un layout o un archivo de metadatos y como una funcionalidad a futuro, una bandera para saber si se descargan una actualización o un layout nuevo.

**Comment by aton1698** [comment]
En mi repositorio, en la rama <a href="https://github.com/aton1698/osmtracker-android/tree/descarga" download>descarga</a> se encuentra el código de una prueba realizada con un botón desde el layout `about`.

**Comment by jamescr** [comment]
Esto tiene que ver con el PR #92

**Comment by jamescr** [comment]
Falta subir el Install en `Available Layouts`.
