### ISSUE TITLE
Pop-up de Buttons Presets (GUI) 

### ISSUE THREAD

**Issue by altaros97** [LabExperimental-SIUA/osmtracker-android#61]
Crear la interfaz del pop-up que cada layout debe llevar, este se debe de abrir cuando se realiza una pulsación larga. Contendrá las opciones de Install and Update y Delete

**Comment by jamescr** [comment]
Para eliminar se puede reutilizar el método `delete` de la [clase `FileSystemUtils`](https://github.com/nguillaumin/osmtracker-android/blob/master/app/src/main/java/me/guillaumin/android/osmtracker/util/FileSystemUtils.java).

**Comment by altaros97** [comment]
Para completar este issue necesito que el issue #59 esté terminado.

**Comment by altaros97** [comment]
Estuve buscando un poco en las clases que N tiene y en [activity/TrackManager](https://github.com/nguillaumin/osmtracker-android/blob/master/app/src/main/java/me/guillaumin/android/osmtracker/activity/TrackManager.java), en el método <code>onOptionsItemSelected</code> se encuentra un ejemplo de utilización de las funciones de borrado en un menú, esto puede servir para la implementación de la funcionalidad cuando la interfaz esté completa.

Añadiendo a esto, encontré un pequeño problema, y es que el evento [setOnLongClickListener](https://developer.android.com/reference/android/view/View.html#setOnLongClickListener(android.view.View.OnLongClickListener)) solo se aplica para elementos de tipo <code>View</code>, nosotros estamos manejando elementos de tipo <code>Preferences</code> y solo existe la forma de hacer ese elemento escuchable a un click y no a una pulsación larga. igualmente, encontré otra forma de desplegar el menú (con un <code>contextMenu</code>), sin embargo, pasa lo mismo que con el <code>LongClick</code>, solo funciona con elementos de tipo <code>View</code>. Si no logro encontrar una manera de aplicar este efecto a un <code>Preferences</code> voto por cambiar la forma de manejar la actividad de <code>ButtonPresets</code>, la misma debería de diseñarse con elementos view y no con elementos preferences.

Referencio al pull request #71 para que tome en cuenta este problema.

**Comment by jamescr** [comment]
Me parece muy bien lo que propone. 

> Referencio al pull request #71 para que tome en cuenta este problema.

Yo prefiero que se haga el merge del PR #71 antes de hacer el cambio al elemento tipo `View`

**Comment by altaros97** [comment]
Igualmente, voy a seguir buscando a ver si encuentro alguna solución pero de lo contrario habría que hacer el cambio e investigar la implementación de <code>Views</code> con el <code>SharedPreferences</code>
