### ISSUE TITLE
Actualiza archivo de metadatos.

### ISSUE THREAD

**Issue by aton1698** [LabExperimental-SIUA/osmtracker-android#64]
Agregar la etiqueta `url` y `version` (en archivos `meta_<nombre layout>.xml`) para el link de descarga del repositorio donde están los xml disponibles para la descarga y la versión respectiva del layout.

**Comment by jamescr** [comment]
El `url` que debemos agregar es el que nos permite hacer una descarga de los archivos utilizando el [api de github](https://developer.github.com/v3/repos/contents/). 

Creo que @aton1698 debería hacer algunas pruebas con #59 para que nos indique con claridad cual debe ser el valor correcto para la etiqueta `url`. Mientras tanto sugiero aguantar un poco el merge de los PR relacionados al issue #64 (ejemplo: #70 ).

Como nota, usando el postman yo probé con el api de github haciendo get desde el url: https://api.github.com/repos/LabExperimental-SIUA/osmtracker-android/contents/layouts?ref=layouts

**Comment by aton1698** [comment]
No recuerdo muy bien para que era que se había acordado el tener la etiqueta URL, el issue #59 se está trabajando para descargar los archivos xml de cada layout, por el momento en las pruebas que hice con una aplicación, guardé el archivo descargado la ruta `/osmtracker/layouts/` en la memoria del celular, sin embargo la ruta se podría modificar.

**Comment by jamescr** [comment]
Si no me equivoco el asunto es porque en #59 se utiliza el "valor de url" que se obtiene de haber consultado los archivos disponibles utilizando el api de github. En esa consulta se requiere el `url` que está en los archivos metadata.

**Comment by EmmanuelAB** [comment]
Cambios al archivo de metadata: 
* Ahora dentro del archivo `metadata` deben agregarse las etiquetas `branch` , `repo` , `username`. Para construir los url's necesarios.
* Ya no es necesaria la etiqueta `version`

**Comment by jamescr** [comment]
**Por hacer:** actualizar el [wiki](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Guide-to-create-Layouts).
