### ISSUE TITLE
Funcionalidad de server settings 

### ISSUE THREAD

**Issue by altaros97** [LabExperimental-SIUA/osmtracker-android#67]
Se necesita el issue #65 listo. Se debe de validar el URL que ingresa el usuario o el default para asegurarnos de que se puede hacer los demás procesos. La validación se realiza cuando se presiona el botón **Ok**, si está mal se presenta mediante un TOAST un mensaje de error al usuario.

**Comment by aton1698** [comment]
Con este <a href="https://github.com/aton1698/osmtracker-android/tree/descarga" download>ejemplo</a> se puede validar si se ingresa una URL valida o no.

**Comment by altaros97** [comment]
Encontré un [método](http://androcode.es/2013/06/verificar-si-un-string-es-una-url-valida/) para válidar primero que sea un URL válido lo que se ingrese y no solo un texto, esto se haría antes de llamar a la funcionalidad que creó @aton1698 y así no gastar recursos montando una conexión en algo que ni si quiera es un URL

**Comment by jamescr** [comment]
Se debe modificar Server Setting para que reciba: usario, repositorio y branch en vez de un url. Con esos tres datos se debe crear los URL de descargas. (se debe corregir el código del PR #83 )

**Comment by altaros97** [comment]
Se relaciona con el issue #86
