### ISSUE TITLE
Cambiar referencias entre actividades de configuración a botones

### ISSUE THREAD

**Issue by EmmanuelAB** [LabExperimental-SIUA/osmtracker-android#73]
Para seguir el diseño inicial

**Comment by altaros97** [comment]
¿Este issue contempla el cambio de <code>Preference</code> a <code>View</code>?

**Comment by EmmanuelAB** [comment]
Sí, voy a empezar a migrar las PreferenceActivities a Activities y cambiar los enlaces entr actividades por botones
