### ISSUE TITLE
Conectar la clase Preferences con la clase ButtonsPresets

### ISSUE THREAD

**Issue by altaros97** [LabExperimental-SIUA/osmtracker-android#82]
Estuve revisando el código de la clase <code>Preferences</code> y al inicio donde se inspecciona el <code>EditTextPreference</code> para seleccionar la carpeta donde se quiere guardar los archivos, con la funcionalidad de N está cada vez que se cambiaba colocaba el layout por defecto dentro de la lista de layouts disponibles (lo cuál ya no tiene importancia en la nueva funcionalidad), pero lo que sí, es que es la referencia (directorio) de donde tenemos que partir para buscar los layouts, es por esto que se necesita conectar esa parte con el string <code>storageDir</code> para que cada vez que la carpeta cambie, esté también cambie.

**Comment by jamescr** [comment]
No entendí muy bien lo del `storageDir`.

**Comment by altaros97** [comment]
Es una variable que está en la clase Buttons Presets, por defecto su valor es <code>/osmtracker</code>, sirve como referencia para leer los layouts que están dentro de la carpeta <code>layouts</code>, a lo que me refería con conectar, es que cuando, dentro del menú de <code>configuraciones</code> (en la app), se cambia el valor del <code>External storage (SD) directory</code>, si alguno de los layouts instalados que no sean el <code>default</code> está activado, la aplicación se cae cuando uno trata de crear una traza. En la funcionalidad de N esto no pasaba, ya que, cuando este valor cambiaba volvía a listar los layouts y activaba el default.

**Comment by jamescr** [comment]
Eso tiene pinta como de una pulga, ¿no?

**Comment by altaros97** [comment]
Si.
