### ISSUE TITLE
Actualizar documentación (screenshots)

### ISSUE THREAD

**Issue by altaros97** [LabExperimental-SIUA/osmtracker-android#86]
Hemos acordado cambiar los datos que se necesitan para la configuración del servidor de donde descargar.

1. Cambiar la actividad <code>Server Setting</code> a <code>GitHub Repository Settings</code>

2. En lugar de solo solicitar un <code>URL</code>, se pasa a solicitar <code>GitHub user name</code>, <code>GitHub repository name</code> y el <code>Branch</code> donde se aloja la estructura indicada en la documentación.  [ver](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Guide-to-create-Layouts)

**Comment by jamescr** [comment]
Al completar este issue verificar si la [wiki](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Guide-to-create-Layouts) está actualizada.
